// Generated by jextract

package io.github.dsheirer.sdrplay.api;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$9 {

    static final FunctionDescriptor sdrplay_api_GetDeviceParams$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle sdrplay_api_GetDeviceParams$MH = RuntimeHelper.downcallHandle(
        sdrplay_api_h.LIBRARIES, "sdrplay_api_GetDeviceParams",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$9.sdrplay_api_GetDeviceParams$FUNC, false
    );
    static final FunctionDescriptor sdrplay_api_Init$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle sdrplay_api_Init$MH = RuntimeHelper.downcallHandle(
        sdrplay_api_h.LIBRARIES, "sdrplay_api_Init",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$9.sdrplay_api_Init$FUNC, false
    );
    static final FunctionDescriptor sdrplay_api_Uninit$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle sdrplay_api_Uninit$MH = RuntimeHelper.downcallHandle(
        sdrplay_api_h.LIBRARIES, "sdrplay_api_Uninit",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$9.sdrplay_api_Uninit$FUNC, false
    );
    static final FunctionDescriptor sdrplay_api_Update$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle sdrplay_api_Update$MH = RuntimeHelper.downcallHandle(
        sdrplay_api_h.LIBRARIES, "sdrplay_api_Update",
        "(Ljdk/incubator/foreign/MemoryAddress;III)I",
        constants$9.sdrplay_api_Update$FUNC, false
    );
    static final FunctionDescriptor sdrplay_api_SwapRspDuoActiveTuner$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_INT
    );
    static final MethodHandle sdrplay_api_SwapRspDuoActiveTuner$MH = RuntimeHelper.downcallHandle(
        sdrplay_api_h.LIBRARIES, "sdrplay_api_SwapRspDuoActiveTuner",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;I)I",
        constants$9.sdrplay_api_SwapRspDuoActiveTuner$FUNC, false
    );
    static final FunctionDescriptor sdrplay_api_SwapRspDuoDualTunerModeSampleRate$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle sdrplay_api_SwapRspDuoDualTunerModeSampleRate$MH = RuntimeHelper.downcallHandle(
        sdrplay_api_h.LIBRARIES, "sdrplay_api_SwapRspDuoDualTunerModeSampleRate",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$9.sdrplay_api_SwapRspDuoDualTunerModeSampleRate$FUNC, false
    );
}


