// Generated by jextract

package io.github.dsheirer.sdrplay.api;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public class sdrplay_api_EventParamsT {

    static final MemoryLayout $union$LAYOUT = MemoryLayout.unionLayout(
        MemoryLayout.structLayout(
            C_INT.withName("gRdB"),
            C_INT.withName("lnaGRdB"),
            C_DOUBLE.withName("currGain")
        ).withName("gainParams"),
        MemoryLayout.structLayout(
            C_INT.withName("powerOverloadChangeType")
        ).withName("powerOverloadParams"),
        MemoryLayout.structLayout(
            C_INT.withName("modeChangeType")
        ).withName("rspDuoModeParams")
    );
    public static MemoryLayout $LAYOUT() {
        return sdrplay_api_EventParamsT.$union$LAYOUT;
    }
    public static MemorySegment gainParams$slice(MemorySegment seg) {
        return seg.asSlice(0, 16);
    }
    public static MemorySegment powerOverloadParams$slice(MemorySegment seg) {
        return seg.asSlice(0, 4);
    }
    public static MemorySegment rspDuoModeParams$slice(MemorySegment seg) {
        return seg.asSlice(0, 4);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.ofScope(scope)); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.ofScope(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


