// Generated by jextract

package io.github.dsheirer.sdrplay.api;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public class sdrplay_api_DcOffsetTunerT {

    static final MemoryLayout $struct$LAYOUT = MemoryLayout.structLayout(
        C_CHAR.withName("dcCal"),
        C_CHAR.withName("speedUp"),
        MemoryLayout.paddingLayout(16),
        C_INT.withName("trackTime"),
        C_INT.withName("refreshRateTime")
    );
    public static MemoryLayout $LAYOUT() {
        return sdrplay_api_DcOffsetTunerT.$struct$LAYOUT;
    }
    static final VarHandle dcCal$VH = $struct$LAYOUT.varHandle(byte.class, MemoryLayout.PathElement.groupElement("dcCal"));
    public static VarHandle dcCal$VH() {
        return sdrplay_api_DcOffsetTunerT.dcCal$VH;
    }
    public static byte dcCal$get(MemorySegment seg) {
        return (byte)sdrplay_api_DcOffsetTunerT.dcCal$VH.get(seg);
    }
    public static void dcCal$set( MemorySegment seg, byte x) {
        sdrplay_api_DcOffsetTunerT.dcCal$VH.set(seg, x);
    }
    public static byte dcCal$get(MemorySegment seg, long index) {
        return (byte)sdrplay_api_DcOffsetTunerT.dcCal$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void dcCal$set(MemorySegment seg, long index, byte x) {
        sdrplay_api_DcOffsetTunerT.dcCal$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle speedUp$VH = $struct$LAYOUT.varHandle(byte.class, MemoryLayout.PathElement.groupElement("speedUp"));
    public static VarHandle speedUp$VH() {
        return sdrplay_api_DcOffsetTunerT.speedUp$VH;
    }
    public static byte speedUp$get(MemorySegment seg) {
        return (byte)sdrplay_api_DcOffsetTunerT.speedUp$VH.get(seg);
    }
    public static void speedUp$set( MemorySegment seg, byte x) {
        sdrplay_api_DcOffsetTunerT.speedUp$VH.set(seg, x);
    }
    public static byte speedUp$get(MemorySegment seg, long index) {
        return (byte)sdrplay_api_DcOffsetTunerT.speedUp$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void speedUp$set(MemorySegment seg, long index, byte x) {
        sdrplay_api_DcOffsetTunerT.speedUp$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle trackTime$VH = $struct$LAYOUT.varHandle(int.class, MemoryLayout.PathElement.groupElement("trackTime"));
    public static VarHandle trackTime$VH() {
        return sdrplay_api_DcOffsetTunerT.trackTime$VH;
    }
    public static int trackTime$get(MemorySegment seg) {
        return (int)sdrplay_api_DcOffsetTunerT.trackTime$VH.get(seg);
    }
    public static void trackTime$set( MemorySegment seg, int x) {
        sdrplay_api_DcOffsetTunerT.trackTime$VH.set(seg, x);
    }
    public static int trackTime$get(MemorySegment seg, long index) {
        return (int)sdrplay_api_DcOffsetTunerT.trackTime$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void trackTime$set(MemorySegment seg, long index, int x) {
        sdrplay_api_DcOffsetTunerT.trackTime$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle refreshRateTime$VH = $struct$LAYOUT.varHandle(int.class, MemoryLayout.PathElement.groupElement("refreshRateTime"));
    public static VarHandle refreshRateTime$VH() {
        return sdrplay_api_DcOffsetTunerT.refreshRateTime$VH;
    }
    public static int refreshRateTime$get(MemorySegment seg) {
        return (int)sdrplay_api_DcOffsetTunerT.refreshRateTime$VH.get(seg);
    }
    public static void refreshRateTime$set( MemorySegment seg, int x) {
        sdrplay_api_DcOffsetTunerT.refreshRateTime$VH.set(seg, x);
    }
    public static int refreshRateTime$get(MemorySegment seg, long index) {
        return (int)sdrplay_api_DcOffsetTunerT.refreshRateTime$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void refreshRateTime$set(MemorySegment seg, long index, int x) {
        sdrplay_api_DcOffsetTunerT.refreshRateTime$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.ofScope(scope)); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.ofScope(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


