// Generated by jextract

package io.github.dsheirer.sdrplay.api;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public class sdrplay_api_ControlParamsT {

    static final MemoryLayout $struct$LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            C_CHAR.withName("DCenable"),
            C_CHAR.withName("IQenable")
        ).withName("dcOffset"),
        MemoryLayout.structLayout(
            C_CHAR.withName("enable"),
            C_CHAR.withName("decimationFactor"),
            C_CHAR.withName("wideBandSignal")
        ).withName("decimation"),
        MemoryLayout.paddingLayout(24),
        MemoryLayout.structLayout(
            C_INT.withName("enable"),
            C_INT.withName("setPoint_dBfs"),
            C_SHORT.withName("attack_ms"),
            C_SHORT.withName("decay_ms"),
            C_SHORT.withName("decay_delay_ms"),
            C_SHORT.withName("decay_threshold_dB"),
            C_INT.withName("syncUpdate")
        ).withName("agc"),
        C_INT.withName("adsbMode")
    );
    public static MemoryLayout $LAYOUT() {
        return sdrplay_api_ControlParamsT.$struct$LAYOUT;
    }
    public static MemorySegment dcOffset$slice(MemorySegment seg) {
        return seg.asSlice(0, 2);
    }
    public static MemorySegment decimation$slice(MemorySegment seg) {
        return seg.asSlice(2, 3);
    }
    public static MemorySegment agc$slice(MemorySegment seg) {
        return seg.asSlice(8, 20);
    }
    static final VarHandle adsbMode$VH = $struct$LAYOUT.varHandle(int.class, MemoryLayout.PathElement.groupElement("adsbMode"));
    public static VarHandle adsbMode$VH() {
        return sdrplay_api_ControlParamsT.adsbMode$VH;
    }
    public static int adsbMode$get(MemorySegment seg) {
        return (int)sdrplay_api_ControlParamsT.adsbMode$VH.get(seg);
    }
    public static void adsbMode$set( MemorySegment seg, int x) {
        sdrplay_api_ControlParamsT.adsbMode$VH.set(seg, x);
    }
    public static int adsbMode$get(MemorySegment seg, long index) {
        return (int)sdrplay_api_ControlParamsT.adsbMode$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void adsbMode$set(MemorySegment seg, long index, int x) {
        sdrplay_api_ControlParamsT.adsbMode$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.ofScope(scope)); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.ofScope(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


