// Generated by jextract

package io.github.dsheirer.sdrplay.api;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public class sdrplay_api_DcOffsetT {

    static final MemoryLayout $struct$LAYOUT = MemoryLayout.structLayout(
        C_CHAR.withName("DCenable"),
        C_CHAR.withName("IQenable")
    );
    public static MemoryLayout $LAYOUT() {
        return sdrplay_api_DcOffsetT.$struct$LAYOUT;
    }
    static final VarHandle DCenable$VH = $struct$LAYOUT.varHandle(byte.class, MemoryLayout.PathElement.groupElement("DCenable"));
    public static VarHandle DCenable$VH() {
        return sdrplay_api_DcOffsetT.DCenable$VH;
    }
    public static byte DCenable$get(MemorySegment seg) {
        return (byte)sdrplay_api_DcOffsetT.DCenable$VH.get(seg);
    }
    public static void DCenable$set( MemorySegment seg, byte x) {
        sdrplay_api_DcOffsetT.DCenable$VH.set(seg, x);
    }
    public static byte DCenable$get(MemorySegment seg, long index) {
        return (byte)sdrplay_api_DcOffsetT.DCenable$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void DCenable$set(MemorySegment seg, long index, byte x) {
        sdrplay_api_DcOffsetT.DCenable$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle IQenable$VH = $struct$LAYOUT.varHandle(byte.class, MemoryLayout.PathElement.groupElement("IQenable"));
    public static VarHandle IQenable$VH() {
        return sdrplay_api_DcOffsetT.IQenable$VH;
    }
    public static byte IQenable$get(MemorySegment seg) {
        return (byte)sdrplay_api_DcOffsetT.IQenable$VH.get(seg);
    }
    public static void IQenable$set( MemorySegment seg, byte x) {
        sdrplay_api_DcOffsetT.IQenable$VH.set(seg, x);
    }
    public static byte IQenable$get(MemorySegment seg, long index) {
        return (byte)sdrplay_api_DcOffsetT.IQenable$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void IQenable$set(MemorySegment seg, long index, byte x) {
        sdrplay_api_DcOffsetT.IQenable$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.ofScope(scope)); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.ofScope(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


