// Generated by jextract

package io.github.dsheirer.sdrplay.api;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public class sdrplay_api_Rsp2ParamsT {

    static final MemoryLayout $struct$LAYOUT = MemoryLayout.structLayout(
        C_CHAR.withName("extRefOutputEn")
    );
    public static MemoryLayout $LAYOUT() {
        return sdrplay_api_Rsp2ParamsT.$struct$LAYOUT;
    }
    static final VarHandle extRefOutputEn$VH = $struct$LAYOUT.varHandle(byte.class, MemoryLayout.PathElement.groupElement("extRefOutputEn"));
    public static VarHandle extRefOutputEn$VH() {
        return sdrplay_api_Rsp2ParamsT.extRefOutputEn$VH;
    }
    public static byte extRefOutputEn$get(MemorySegment seg) {
        return (byte)sdrplay_api_Rsp2ParamsT.extRefOutputEn$VH.get(seg);
    }
    public static void extRefOutputEn$set( MemorySegment seg, byte x) {
        sdrplay_api_Rsp2ParamsT.extRefOutputEn$VH.set(seg, x);
    }
    public static byte extRefOutputEn$get(MemorySegment seg, long index) {
        return (byte)sdrplay_api_Rsp2ParamsT.extRefOutputEn$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void extRefOutputEn$set(MemorySegment seg, long index, byte x) {
        sdrplay_api_Rsp2ParamsT.extRefOutputEn$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.ofScope(scope)); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.ofScope(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


