// Generated by jextract

package io.github.dsheirer.sdrplay.api;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public class sdrplay_api_DecimationT {

    static final MemoryLayout $struct$LAYOUT = MemoryLayout.structLayout(
        C_CHAR.withName("enable"),
        C_CHAR.withName("decimationFactor"),
        C_CHAR.withName("wideBandSignal")
    );
    public static MemoryLayout $LAYOUT() {
        return sdrplay_api_DecimationT.$struct$LAYOUT;
    }
    static final VarHandle enable$VH = $struct$LAYOUT.varHandle(byte.class, MemoryLayout.PathElement.groupElement("enable"));
    public static VarHandle enable$VH() {
        return sdrplay_api_DecimationT.enable$VH;
    }
    public static byte enable$get(MemorySegment seg) {
        return (byte)sdrplay_api_DecimationT.enable$VH.get(seg);
    }
    public static void enable$set( MemorySegment seg, byte x) {
        sdrplay_api_DecimationT.enable$VH.set(seg, x);
    }
    public static byte enable$get(MemorySegment seg, long index) {
        return (byte)sdrplay_api_DecimationT.enable$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void enable$set(MemorySegment seg, long index, byte x) {
        sdrplay_api_DecimationT.enable$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle decimationFactor$VH = $struct$LAYOUT.varHandle(byte.class, MemoryLayout.PathElement.groupElement("decimationFactor"));
    public static VarHandle decimationFactor$VH() {
        return sdrplay_api_DecimationT.decimationFactor$VH;
    }
    public static byte decimationFactor$get(MemorySegment seg) {
        return (byte)sdrplay_api_DecimationT.decimationFactor$VH.get(seg);
    }
    public static void decimationFactor$set( MemorySegment seg, byte x) {
        sdrplay_api_DecimationT.decimationFactor$VH.set(seg, x);
    }
    public static byte decimationFactor$get(MemorySegment seg, long index) {
        return (byte)sdrplay_api_DecimationT.decimationFactor$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void decimationFactor$set(MemorySegment seg, long index, byte x) {
        sdrplay_api_DecimationT.decimationFactor$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle wideBandSignal$VH = $struct$LAYOUT.varHandle(byte.class, MemoryLayout.PathElement.groupElement("wideBandSignal"));
    public static VarHandle wideBandSignal$VH() {
        return sdrplay_api_DecimationT.wideBandSignal$VH;
    }
    public static byte wideBandSignal$get(MemorySegment seg) {
        return (byte)sdrplay_api_DecimationT.wideBandSignal$VH.get(seg);
    }
    public static void wideBandSignal$set( MemorySegment seg, byte x) {
        sdrplay_api_DecimationT.wideBandSignal$VH.set(seg, x);
    }
    public static byte wideBandSignal$get(MemorySegment seg, long index) {
        return (byte)sdrplay_api_DecimationT.wideBandSignal$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void wideBandSignal$set(MemorySegment seg, long index, byte x) {
        sdrplay_api_DecimationT.wideBandSignal$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.ofScope(scope)); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.ofScope(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


