// Generated by jextract

package io.github.dsheirer.sdrplay.api.v3_07;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$7 {

    static final FunctionDescriptor sdrplay_api_Open$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle sdrplay_api_Open$MH = RuntimeHelper.downcallHandle(
        "sdrplay_api_Open",
        constants$7.sdrplay_api_Open$FUNC, false
    );
    static final FunctionDescriptor sdrplay_api_Close$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle sdrplay_api_Close$MH = RuntimeHelper.downcallHandle(
        "sdrplay_api_Close",
        constants$7.sdrplay_api_Close$FUNC, false
    );
    static final FunctionDescriptor sdrplay_api_ApiVersion$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sdrplay_api_ApiVersion$MH = RuntimeHelper.downcallHandle(
        "sdrplay_api_ApiVersion",
        constants$7.sdrplay_api_ApiVersion$FUNC, false
    );
    static final FunctionDescriptor sdrplay_api_LockDeviceApi$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle sdrplay_api_LockDeviceApi$MH = RuntimeHelper.downcallHandle(
        "sdrplay_api_LockDeviceApi",
        constants$7.sdrplay_api_LockDeviceApi$FUNC, false
    );
    static final FunctionDescriptor sdrplay_api_UnlockDeviceApi$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle sdrplay_api_UnlockDeviceApi$MH = RuntimeHelper.downcallHandle(
        "sdrplay_api_UnlockDeviceApi",
        constants$7.sdrplay_api_UnlockDeviceApi$FUNC, false
    );
    static final FunctionDescriptor sdrplay_api_GetDevices$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle sdrplay_api_GetDevices$MH = RuntimeHelper.downcallHandle(
        "sdrplay_api_GetDevices",
        constants$7.sdrplay_api_GetDevices$FUNC, false
    );
}


