// Generated by jextract

package io.github.dsheirer.sdrplay.api.v3_07;

import java.lang.invoke.MethodHandle;

import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$1 {

    static final FunctionDescriptor sdrplay_api_Close_t$FUNC = FunctionDescriptor.of(C_INT);
    static final MethodHandle sdrplay_api_Close_t$MH = RuntimeHelper.downcallHandle(
        "()I",
        constants$1.sdrplay_api_Close_t$FUNC, false
    );
    static final FunctionDescriptor sdrplay_api_ApiVersion_t$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle sdrplay_api_ApiVersion_t$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$1.sdrplay_api_ApiVersion_t$FUNC, false
    );
    static final FunctionDescriptor sdrplay_api_LockDeviceApi_t$FUNC = FunctionDescriptor.of(C_INT);
    static final MethodHandle sdrplay_api_LockDeviceApi_t$MH = RuntimeHelper.downcallHandle(
        "()I",
        constants$1.sdrplay_api_LockDeviceApi_t$FUNC, false
    );
}


