// Generated by jextract

package io.github.dsheirer.sdrplay.api.v3_07;

import java.lang.invoke.MethodHandle;

import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$10 {

    static final FunctionDescriptor sdrplay_api_SwapRspDuoMode$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_INT,
        C_DOUBLE,
        C_INT,
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle sdrplay_api_SwapRspDuoMode$MH = RuntimeHelper.downcallHandle(
        sdrplay_api_h.LIBRARIES, "sdrplay_api_SwapRspDuoMode",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;IDIIII)I",
        constants$10.sdrplay_api_SwapRspDuoMode$FUNC, false
    );
}


