// Generated by jextract

package io.github.dsheirer.sdrplay.api.v3_07;

import jdk.incubator.foreign.*;

public interface sdrplay_api_Update_t {

    int apply(jdk.incubator.foreign.MemoryAddress x0, int x1, int x2, int x3);
    static MemoryAddress allocate(sdrplay_api_Update_t fi) {
        return RuntimeHelper.upcallStub(sdrplay_api_Update_t.class, fi, constants$5.sdrplay_api_Update_t$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;III)I");
    }
    static MemoryAddress allocate(sdrplay_api_Update_t fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(sdrplay_api_Update_t.class, fi, constants$5.sdrplay_api_Update_t$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;III)I", scope);
    }
    static sdrplay_api_Update_t ofAddress(MemoryAddress addr) {
        return (jdk.incubator.foreign.MemoryAddress x0, int x1, int x2, int x3) -> {
            try {
                return (int)constants$5.sdrplay_api_Update_t$MH.invokeExact((Addressable)addr, x0, x1, x2, x3);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


