// Generated by jextract

package io.github.dsheirer.sdrplay.api.v3_07;

import jdk.incubator.foreign.*;

public interface sdrplay_api_Uninit_t {

    int apply(jdk.incubator.foreign.MemoryAddress x0);
    static MemoryAddress allocate(sdrplay_api_Uninit_t fi) {
        return RuntimeHelper.upcallStub(sdrplay_api_Uninit_t.class, fi, constants$5.sdrplay_api_Uninit_t$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I");
    }
    static MemoryAddress allocate(sdrplay_api_Uninit_t fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(sdrplay_api_Uninit_t.class, fi, constants$5.sdrplay_api_Uninit_t$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I", scope);
    }
    static sdrplay_api_Uninit_t ofAddress(MemoryAddress addr) {
        return (jdk.incubator.foreign.MemoryAddress x0) -> {
            try {
                return (int)constants$5.sdrplay_api_Uninit_t$MH.invokeExact((Addressable)addr, x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


