// Generated by jextract

package io.github.dsheirer.sdrplay.api.v3_07;

import jdk.incubator.foreign.*;

public interface sdrplay_api_UnlockDeviceApi_t {

    int apply();
    static MemoryAddress allocate(sdrplay_api_UnlockDeviceApi_t fi) {
        return RuntimeHelper.upcallStub(sdrplay_api_UnlockDeviceApi_t.class, fi, constants$2.sdrplay_api_UnlockDeviceApi_t$FUNC, "()I");
    }
    static MemoryAddress allocate(sdrplay_api_UnlockDeviceApi_t fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(sdrplay_api_UnlockDeviceApi_t.class, fi, constants$2.sdrplay_api_UnlockDeviceApi_t$FUNC, "()I", scope);
    }
    static sdrplay_api_UnlockDeviceApi_t ofAddress(MemoryAddress addr) {
        return () -> {
            try {
                return (int)constants$2.sdrplay_api_UnlockDeviceApi_t$MH.invokeExact((Addressable)addr);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


