// Generated by jextract

package com.github.dsheirer.sdrplay.api.v3_07;

import jdk.incubator.foreign.*;

public interface sdrplay_api_Close_t {

    int apply();
    static NativeSymbol allocate(sdrplay_api_Close_t fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(sdrplay_api_Close_t.class, fi, constants$1.sdrplay_api_Close_t$FUNC, "()I", scope);
    }
    static sdrplay_api_Close_t ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("sdrplay_api_Close_t::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return () -> {
            try {
                return (int)constants$1.sdrplay_api_Close_t$MH.invokeExact(symbol);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


