// Generated by jextract

package com.github.dsheirer.sdrplay.api.v3_07;

import jdk.incubator.foreign.*;

public interface sdrplay_api_DebugEnable_t {

    int apply(jdk.incubator.foreign.MemoryAddress x0, int x1);
    static NativeSymbol allocate(sdrplay_api_DebugEnable_t fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(sdrplay_api_DebugEnable_t.class, fi, constants$4.sdrplay_api_DebugEnable_t$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;I)I", scope);
    }
    static sdrplay_api_DebugEnable_t ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("sdrplay_api_DebugEnable_t::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (jdk.incubator.foreign.MemoryAddress x0, int x1) -> {
            try {
                return (int)constants$4.sdrplay_api_DebugEnable_t$MH.invokeExact(symbol, (jdk.incubator.foreign.Addressable)x0, x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


