// Generated by jextract

package com.github.dsheirer.sdrplay.api.v3_07;

import java.lang.invoke.VarHandle;
import jdk.incubator.foreign.*;

public class sdrplay_api_ControlParamsT {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            Constants$root.C_CHAR$LAYOUT.withName("DCenable"),
            Constants$root.C_CHAR$LAYOUT.withName("IQenable")
        ).withName("dcOffset"),
        MemoryLayout.structLayout(
            Constants$root.C_CHAR$LAYOUT.withName("enable"),
            Constants$root.C_CHAR$LAYOUT.withName("decimationFactor"),
            Constants$root.C_CHAR$LAYOUT.withName("wideBandSignal")
        ).withName("decimation"),
        MemoryLayout.paddingLayout(24),
        MemoryLayout.structLayout(
            Constants$root.C_INT$LAYOUT.withName("enable"),
            Constants$root.C_INT$LAYOUT.withName("setPoint_dBfs"),
            Constants$root.C_SHORT$LAYOUT.withName("attack_ms"),
            Constants$root.C_SHORT$LAYOUT.withName("decay_ms"),
            Constants$root.C_SHORT$LAYOUT.withName("decay_delay_ms"),
            Constants$root.C_SHORT$LAYOUT.withName("decay_threshold_dB"),
            Constants$root.C_INT$LAYOUT.withName("syncUpdate")
        ).withName("agc"),
        Constants$root.C_INT$LAYOUT.withName("adsbMode")
    );
    public static MemoryLayout $LAYOUT() {
        return sdrplay_api_ControlParamsT.$struct$LAYOUT;
    }
    public static MemorySegment dcOffset$slice(MemorySegment seg) {
        return seg.asSlice(0, 2);
    }
    public static MemorySegment decimation$slice(MemorySegment seg) {
        return seg.asSlice(2, 3);
    }
    public static MemorySegment agc$slice(MemorySegment seg) {
        return seg.asSlice(8, 20);
    }
    static final VarHandle adsbMode$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("adsbMode"));
    public static VarHandle adsbMode$VH() {
        return sdrplay_api_ControlParamsT.adsbMode$VH;
    }
    public static int adsbMode$get(MemorySegment seg) {
        return (int)sdrplay_api_ControlParamsT.adsbMode$VH.get(seg);
    }
    public static void adsbMode$set( MemorySegment seg, int x) {
        sdrplay_api_ControlParamsT.adsbMode$VH.set(seg, x);
    }
    public static int adsbMode$get(MemorySegment seg, long index) {
        return (int)sdrplay_api_ControlParamsT.adsbMode$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void adsbMode$set(MemorySegment seg, long index, int x) {
        sdrplay_api_ControlParamsT.adsbMode$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.nativeAllocator(scope)); }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.nativeAllocator(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


